# Generated by Django 4.0.4 on 2022-06-04 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idt', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('sire_id', models.IntegerField(null=True)),
                ('dam_id', models.IntegerField(null=True)),
                ('animal_type', models.CharField(choices=[('Cow', 'Cow'), ('Goat', 'Goat'), ('Chicken', 'Chicken'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Pig', 'Pig'), ('Duck', 'Duck')], max_length=200, null=True)),
                ('ear_tag', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('pasture', models.CharField(max_length=200, null=True)),
                ('birth_rate', models.CharField(max_length=200, null=True)),
                ('current_age', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('first_age', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('contact', models.CharField(max_length=1000, null=True)),
                ('amount', models.CharField(max_length=1000, null=True)),
                ('date_bought', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('date_incurred', models.DateTimeField(default=django.utils.timezone.now)),
                ('type2', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('diagnosis', models.CharField(max_length=1000, null=True)),
                ('treatment', models.CharField(max_length=200, null=True)),
                ('cost', models.CharField(max_length=200, null=True)),
                ('vet', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healthreports', to='animal.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(null=True, unique=True)),
                ('emp_name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(choices=[('Administrator', 'Administrator'), ('Regular', 'Regular'), ('Employee', 'Employee')], max_length=200, null=True)),
                ('salary', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_diagnosis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('calve_due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_calved', models.DateTimeField(default=django.utils.timezone.now)),
                ('calf_notes', models.CharField(max_length=1000, null=True)),
                ('bull', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullbreedings', to='animal.animal')),
                ('calf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calfbreedings', to='animal.animal')),
            ],
        ),
    ]
