# Generated by Django 4.0.4 on 2022-06-04 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_rename_calve_due_date_breeding_breeding_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeding',
            name='calve_due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
