# Generated by Django 4.0.4 on 2022-06-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_breeding_calve_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
