# Generated by Django 4.0.4 on 2022-06-06 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_alter_employee_salary_alter_finance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
